# Generated by Django 5.2.3 on 2025-07-25 04:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.PositiveIntegerField(default=465, verbose_name='Porta SMTP')),
                ('smtp_user', models.EmailField(max_length=254, verbose_name='Usuário SMTP')),
                ('smtp_password', models.CharField(max_length=255, verbose_name='Senha APP')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Usar TLS?')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Usar SSL?')),
                ('default_from_email', models.EmailField(max_length=254, verbose_name='Remetente Padrão')),
                ('test_recipient', models.EmailField(blank=True, help_text='E-mail para receber os envios de teste.', max_length=254, null=True, verbose_name='Destinatário de Teste')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
                'db_table': 'tb_NotifyEmailConfig',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Notificação')),
                ('subject', models.CharField(max_length=255, verbose_name='Assunto do E-mail')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Corpo do E-mail')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Template de Notificação',
                'verbose_name_plural': 'Templates de Notificação',
                'db_table': 'tb_NotifyConfigTemplate',
            },
        ),
    ]
