# Generated by Django 5.2.3 on 2025-07-14 12:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Corpo do E-mail'),
        ),
    ]
