# Generated by Django 5.2.3 on 2025-08-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyconfig',
            options={'verbose_name': 'Configuração de E-mail', 'verbose_name_plural': 'Configurações de E-mail'},
        ),
    ]
