# Generated by Django 5.2.3 on 2025-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='test_recipient',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Destinatário de Teste'),
        ),
    ]
