# Generated by Django 5.2.3 on 2025-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_emailconfig_test_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='test_recipient',
            field=models.EmailField(blank=True, help_text='E-mail para receber os envios de teste.', max_length=254, null=True, verbose_name='Destinatário de Teste'),
        ),
    ]
