# Generated by Django 5.2.3 on 2025-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_emailconfig_test_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_password',
            field=models.CharField(max_length=255, verbose_name='Senha APP'),
        ),
    ]
