"""
Django settings for fazenergy project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u(q$1ovg$dj*!89iqs)xq8!n$e5ea3ckjs9&+od(amr$(k68k3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'finance.apps.FinanceConfig',
    'core',
    'network',
    'plans',
    'location',
    'notifications',
    'ckeditor',
    'contracts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True # Permita CORS para o frontend rodar separado:

AUTH_USER_MODEL = 'core.User'

ROOT_URLCONF = 'config.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# caso queira customizar o chkeditor
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         'height': 300,
#         'width': '100%',
#     },
# }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLLITE
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#SQLLOCAL:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_FazEnergyVue',
        'USER': 'postgres',
        'PASSWORD': 'Prime@2025',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
DATE_FORMAT = "d/m/Y"           # Exibe como 03/07/2025
DATETIME_FORMAT = "d/m/Y H:i"  # Formato padrão para datas com hora

# Formato de entrada (quando você digita no admin ou form)
DATE_INPUT_FORMATS = ["%d/%m/%Y"]
DATETIME_INPUT_FORMATS = ["%d/%m/%Y %H:%M"]

USE_I18N = True
USE_L10N = False  # Desativa formatação automática baseada no locale
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



##########################################################################
# Celery Configuration
##########################################################################
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# como rodar o Celery: celery -A config worker --loglevel=info



##########################################################################
# # Jazzmin Configuration | Painel Admin Customizado
##########################################################################
# JAZZMIN_SETTINGS = {
#     "site_header": "FazEnergy Adm",
#     "site_title": "Painel Admin FazEnergy",
#     "site.index_title": "Bem-vindo!",
#     #"site_logo": "img/logo.svg",          # Ícone no topo
#     "site_brand": "FazEnergy",
#     "welcome_sign": "Bem-vindo ao Painel Admin FazEnergy",
#     "copyright": "Copyright © 2025 FazEnergy",    
#     "color_scheme": "black",  # Escolha um esquema de cores
#     "show_ui_builder": True,  # Desabilita o construtor de UI
#     "show_sidebar": True,
#     "navigation_expanded": False,  # inicia fechado!
# }


JAZZMIN_SETTINGS = {
    "site_title": "Painel Administrativo",
    "site_header": "FazEnergy Admin",
    "site_brand": "FazEnergy",
    "site_logo": "logo-fz.png",          # Ícone no topo
    "site_icon": "favicon.ico",
    "welcome_sign": "Bem-vindo ao Painel FazEnergy",
    "copyright": "FazEnergy © 2025",

    "navigation_expanded": False,  # Inicia os apps fechados (accordion)
    "show_sidebar": True,
    "hide_apps": [],  # Apps que quer ocultar do menu
    "hide_models": [],  # Models que quer ocultar do menu

    "order_with_respect_to": [
        "core",
        "finance",
        "notifications",
        "location",
    ],

    "icons": {
        "auth": "fas fa-users",
        "finance": "fas fa-coins",
        "core.Affiliate": "fas fa-user-tie",
        "finance.PaymentLink": "fas fa-link",
    },

    "custom_css": None,
    "custom_js": None,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "pulse",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

