services:
  db:
    image: postgres:15
    container_name: fazenergy-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: fazenergy-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    env_file:
      - .env
    user: "${UID}:${GID}"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: fazenergy-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # impede conflito com node_modules local
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  pgdata:
