# Generated by Django 5.2.3 on 2025-08-01 06:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexio_url', models.URLField(default='https://app.lexio.legal/api/receive_document')),
                ('lexio_token', models.CharField(max_length=255, verbose_name='Token de API')),
                ('signer_company_name', models.CharField(max_length=255, verbose_name='Nome Parte Contratante')),
                ('signer_company_email', models.EmailField(max_length=254, verbose_name='E-mail Parte Contratante')),
                ('signer_company_function', models.CharField(default='Parte Contratante', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração Lexio',
                'verbose_name_plural': 'Configurações Lexio',
                'db_table': 'ContractConfig',
            },
        ),
        migrations.CreateModel(
            name='ContractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_token', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Contrato',
                'verbose_name_plural': 'Log de Contrato',
                'db_table': 'ContractLog',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Contrato')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo do Contrato (HTML)')),
                ('mapping_info', models.TextField(blank=True, help_text='Tabela de chaves disponíveis para usar no contrato.', null=True, verbose_name='Instruções de Mapeamento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Template de Contrato',
                'verbose_name_plural': 'Templates de Contrato',
                'db_table': 'ContractTemplate',
            },
        ),
    ]
