# Generated by Django 5.2.3 on 2025-07-14 20:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexio_url', models.URLField(default='https://app.lexio.legal/api/receive_document')),
                ('lexio_token', models.CharField(max_length=255, verbose_name='Token de API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração Lexio',
                'verbose_name_plural': 'Configurações Lexio',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome do Contrato')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Conteúdo do Contrato (HTML)')),
                ('mapping_info', models.TextField(blank=True, help_text='Tabela de chaves disponíveis para usar no contrato.', null=True, verbose_name='Instruções de Mapeamento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Template de Contrato',
                'verbose_name_plural': 'Templates de Contrato',
            },
        ),
    ]
