# Generated by Django 5.2.3 on 2025-07-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconfig',
            name='signer_company_email',
            field=models.EmailField(default='admin@fazenergy.com.br', max_length=254, verbose_name='E-mail Parte Contratante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_company_function',
            field=models.CharField(default='Parte Contratante', max_length=255),
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_company_name',
            field=models.CharField(default='admin@faz.energy', max_length=255, verbose_name='Nome Parte Contratante'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContractLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_token', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affiliate')),
                ('contract_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttemplate')),
            ],
        ),
    ]
