# Generated by Django 5.2.3 on 2025-07-25 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractlog',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affiliate'),
        ),
        migrations.AddField(
            model_name='contractlog',
            name='contract_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttemplate'),
        ),
    ]
