# Generated by Django 5.2.3 on 2025-08-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractconfig',
            name='signer_company_email',
        ),
        migrations.RemoveField(
            model_name='contractconfig',
            name='signer_company_function',
        ),
        migrations.RemoveField(
            model_name='contractconfig',
            name='signer_company_name',
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_mail_partner',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail Parte Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_mail_testmon',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail Testemunha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_name_partner',
            field=models.CharField(default=1, max_length=255, verbose_name='Parte da Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractconfig',
            name='signer_name_testmon',
            field=models.CharField(default=1, max_length=255, verbose_name='Testemunha'),
            preserve_default=False,
        ),
    ]
