# Generated by Django 5.2.3 on 2025-09-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0009_drop_contractor_pref_and_bill'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE \"ContractorProposalResult\" RENAME COLUMN contract_duration_months TO contract_duration;",
            reverse_sql="ALTER TABLE \"ContractorProposalResult\" RENAME COLUMN contract_duration TO contract_duration_months;"
        ),
    ]
