# Generated by Django 5.2.3 on 2025-09-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0011_bootstrap_lead_actor'),
        ('contractor', '0012_drop_response_payload_post'),
    ]

    operations = [
    ]
