# Generated by Django 5.2.3 on 2025-06-29 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.PositiveIntegerField()),
                ('bonus_level_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dtt_record', models.DateTimeField(auto_now_add=True)),
                ('dtt_update', models.DateTimeField(auto_now=True)),
                ('stt_record', models.BooleanField(default=True)),
                ('usr_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('usr_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
