# Generated by Django 5.2.3 on 2025-08-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCareer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, verbose_name='Estágio')),
                ('reward_description', models.CharField(max_length=255, verbose_name='Prêmio')),
                ('required_points', models.PositiveIntegerField(verbose_name='Pontos Necessários')),
                ('required_directs', models.PositiveSmallIntegerField(verbose_name='Quantidade de Diretos')),
                ('required_direct_sales', models.PositiveSmallIntegerField(verbose_name='Vendas Diretas')),
                ('max_pml_per_line', models.PositiveIntegerField(verbose_name='Pontos Máximos por Linha (PML)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='plan_careers/', verbose_name='Imagem de Capa')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('stt_record', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Plano de Carreira',
                'verbose_name_plural': 'Planos de Carreira',
                'db_table': 'PlanCareers',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points', models.PositiveIntegerField()),
                ('bonus_level_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_level_5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stt_record', models.BooleanField(default=True)),
                ('dtt_record', models.DateTimeField(auto_now_add=True)),
                ('dtt_update', models.DateTimeField(auto_now=True)),
                ('contract_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate', verbose_name='Template de Contrato')),
                ('usr_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('usr_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='PlanAdesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_payment_status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('typ_payment', models.CharField(blank=True, choices=[('pix', 'Pix'), ('money', 'Dinheiro'), ('creditCard', 'Cartão de Crédito'), ('debitCard', 'Cartão de Débito')], max_length=20, null=True)),
                ('dtt_record', models.DateTimeField(auto_now_add=True)),
                ('dtt_payment', models.DateTimeField(blank=True, null=True)),
                ('dtt_cancel', models.DateTimeField(blank=True, null=True)),
                ('dtt_update', models.DateTimeField(auto_now=True)),
                ('is_courtesy', models.BooleanField(default=False)),
                ('points_generated', models.BooleanField(default=False)),
                ('ind_processing', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('ind_bonus_status', models.CharField(choices=[('notApply', 'Não Aplicável'), ('pendingPayment', 'Pagamento Pendente'), ('bonusApplied', 'Bônus Aplicado'), ('cancelBonus', 'Cancelar Bônus'), ('bonusCanceled', 'Bônus Cancelado')], default='notApply', max_length=20)),
                ('des_cancel_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_status', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_token', models.CharField(blank=True, max_length=500, null=True)),
                ('licensed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Plano de Adesão',
                'verbose_name_plural': 'Planos de Adesão',
                'db_table': 'PlanAdesion',
            },
        ),
    ]
