# Generated by Django 5.2.3 on 2025-08-12 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='bonus_level_1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bônus Nível 1'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bonus_level_2',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bônus Nível 2'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bonus_level_3',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bônus Nível 3'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bonus_level_4',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bônus Nível 4'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bonus_level_5',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bônus Nível 5'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dtt_record',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Criação'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='dtt_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Atualização'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/', verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Plano'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='points',
            field=models.PositiveIntegerField(verbose_name='Pontos'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stt_record',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='usr_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL, verbose_name='User Record'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='usr_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_updated', to=settings.AUTH_USER_MODEL, verbose_name='User Update'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='contract_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Contrato'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='contract_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Token Contrato'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='des_cancel_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo Cancelamento'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='ind_bonus_status',
            field=models.CharField(choices=[('notApply', 'Não Aplicável'), ('pendingPayment', 'Pagamento Pendente'), ('bonusApplied', 'Bônus Aplicado'), ('cancelBonus', 'Cancelar Bônus'), ('bonusCanceled', 'Bônus Cancelado')], default='notApply', max_length=20, verbose_name='Stt Bônus'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='ind_payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Stt Pagamento'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='ind_processing',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Stt Process'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='is_courtesy',
            field=models.BooleanField(default=False, verbose_name='Cortesia?'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='licensed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to=settings.AUTH_USER_MODEL, verbose_name='Licenciado'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to='plans.plan', verbose_name='Plano de Adesão'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='points_generated',
            field=models.BooleanField(default=False, verbose_name='Pontos'),
        ),
        migrations.AlterField(
            model_name='planadesion',
            name='typ_payment',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('money', 'Dinheiro'), ('creditCard', 'Cartão de Crédito'), ('debitCard', 'Cartão de Débito')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='plancareer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='plancareer',
            name='max_pml_per_line',
            field=models.PositiveIntegerField(verbose_name='Pontos Máx por Linha (PML)'),
        ),
        migrations.AlterField(
            model_name='plancareer',
            name='required_directs',
            field=models.PositiveSmallIntegerField(verbose_name='Qtd de Diretos'),
        ),
    ]
