# Generated by Django 5.2.3 on 2025-06-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAdesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_payment_status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('typ_payment', models.CharField(blank=True, choices=[('pix', 'Pix'), ('money', 'Dinheiro'), ('creditCard', 'Cartão de Crédito'), ('debitCard', 'Cartão de Débito')], max_length=20, null=True)),
                ('dtt_record', models.DateTimeField(auto_now_add=True)),
                ('dtt_payment', models.DateTimeField(blank=True, null=True)),
                ('dtt_cancel', models.DateTimeField(blank=True, null=True)),
                ('dtt_update', models.DateTimeField(auto_now=True)),
                ('is_courtesy', models.BooleanField(default=False)),
                ('points_generated', models.BooleanField(default=False)),
                ('ind_processing', models.CharField(choices=[('pending', 'Pendente'), ('success', 'Sucesso'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('ind_bonus_status', models.CharField(choices=[('notApply', 'Não Aplicável'), ('pendingPayment', 'Pagamento Pendente'), ('bonusApplied', 'Bônus Aplicado'), ('cancelBonus', 'Cancelar Bônus'), ('bonusCanceled', 'Bônus Cancelado')], default='notApply', max_length=20)),
                ('des_cancel_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('contract_status', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_token', models.CharField(blank=True, max_length=500, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adesions', to='plans.plan')),
            ],
        ),
    ]
