# Generated by Django 5.2.3 on 2025-06-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_planadesion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plan',
            table='tb_Plan',
        ),
        migrations.AlterModelTable(
            name='planadesion',
            table='tb_PlanAdesion',
        ),
    ]
