# Generated by Django 5.2.3 on 2025-07-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_table_alter_planadesion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, verbose_name='Estágio')),
                ('reward_description', models.CharField(max_length=255, verbose_name='Prêmio')),
                ('required_points', models.PositiveIntegerField(verbose_name='Pontos Necessários')),
                ('required_directs', models.PositiveSmallIntegerField(verbose_name='Quantidade de Diretos')),
                ('required_direct_sales', models.PositiveSmallIntegerField(verbose_name='Vendas Diretas')),
                ('max_pml_per_line', models.PositiveIntegerField(verbose_name='Pontos Máximos por Linha (PML)')),
                ('stt_record', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
            ],
            options={
                'verbose_name': 'Plano de Carreira',
                'verbose_name_plural': 'Planos de Carreira',
                'db_table': 'tb_PlanCareers',
            },
        ),
    ]
