# Generated by Django 5.2.3 on 2025-08-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_create_qualification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qualification',
            new_name='Qualificati_license_7a7138_idx',
            old_name='plans_quali_licensed_idx',
        ),
        migrations.RenameIndex(
            model_name='qualification',
            new_name='Qualificati_plan_ca_6b30ba_idx',
            old_name='plans_quali_career_idx',
        ),
    ]
