# Generated by Django 5.2.3 on 2025-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plancareer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='planadesion',
            options={'verbose_name': 'Plano de Adesão', 'verbose_name_plural': 'Planos de Adesão'},
        ),
        migrations.AddField(
            model_name='plancareer',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_careers/', verbose_name='Imagem de Capa'),
        ),
    ]
