# Generated by Django 5.2.3 on 2025-08-16 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_scorereference'),
        ('plans', '0004_auto_20250816_0223'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qualification',
            new_name='Qualificati_license_7a7138_idx',
            old_name='plans_quali_licensed_idx',
        ),
        migrations.RenameIndex(
            model_name='qualification',
            new_name='Qualificati_plan_ca_6b30ba_idx',
            old_name='plans_quali_career_idx',
        ),
        migrations.AddField(
            model_name='planadesion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_adesions', to='network.product', verbose_name='Produto'),
        ),
    ]
