# Generated by Django 5.2.3 on 2025-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_rename_plans_quali_licensed_idx_qualificati_license_7a7138_idx_and_more'),
        ('plans', '0005_rename_plans_quali_licensed_idx_qualificati_license_7a7138_idx_and_more'),
    ]

    operations = [
    ]
