# Generated by Django 5.2.3 on 2025-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_plan_options_alter_planadesion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancareer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
