# Generated by Django 5.2.3 on 2025-07-14 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractconfig_signer_company_email_and_more'),
        ('plans', '0006_alter_plancareer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='contract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate', verbose_name='Template de Contrato'),
        ),
    ]
