# Generated by Django 5.2.3 on 2025-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_add_audit_fields_plan_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='validity_months',
            field=models.PositiveIntegerField(default=12, verbose_name='Validade (meses)'),
        ),
    ]
