# Generated by Django 5.2.3 on 2025-07-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateNetworkPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('points', models.PositiveIntegerField(verbose_name='Pontos')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
                ('dtt_reference', models.DateTimeField(verbose_name='Data de Referência')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('blocked', 'Bloqueado'), ('canceled', 'Cancelado')], default='active', max_length=20, verbose_name='Status')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_points', to='core.affiliate', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Pontos da Rede do Afiliado',
                'verbose_name_plural': 'Pontos da Rede dos Afiliados',
                'db_table': 'tb_AffiliateNetworkPoints',
            },
        ),
        migrations.CreateModel(
            name='UnilevelStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Nível na Rede')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('child_affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.affiliate', verbose_name='Afiliado Filho')),
                ('parent_affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.affiliate', verbose_name='Afiliado Pai')),
            ],
            options={
                'verbose_name': 'Estrutura Unilevel',
                'verbose_name_plural': 'Estruturas Unilevel',
                'db_table': 'tb_UnilevelStructure',
            },
        ),
    ]
