# Generated by Django 5.2.3 on 2025-07-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pontos')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência')),
                ('dtt_ref', models.DateField(verbose_name='Data Referência')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Registro')),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('pending', 'Pendente'), ('canceled', 'Cancelado')], default='valid', max_length=20, verbose_name='Status')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.affiliate', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Pontuação do Afiliado',
                'verbose_name_plural': 'Pontuações dos Afiliados',
                'db_table': 'tb_AffiliatePoints',
                'indexes': [models.Index(fields=['affiliate'], name='tb_Affiliat_affilia_bf176c_idx'), models.Index(fields=['status'], name='tb_Affiliat_status_c41566_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnilevelNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Nível na Rede')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Registro')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('child_affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.affiliate', verbose_name='Afiliado Filho')),
                ('parent_affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.affiliate', verbose_name='Afiliado Pai')),
            ],
            options={
                'verbose_name': 'Rede Unilevel',
                'verbose_name_plural': 'Rede Unilevel',
                'db_table': 'tb_UnilevelNetwork',
                'indexes': [models.Index(fields=['parent_affiliate'], name='tb_Unilevel_parent__a033fb_idx'), models.Index(fields=['child_affiliate'], name='tb_Unilevel_child_a_f9d8d6_idx')],
            },
        ),
    ]
