# Generated by Django 5.2.3 on 2025-08-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensedPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pontos')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência')),
                ('dtt_ref', models.DateField(verbose_name='Data Referência')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Registro')),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('pending', 'Pendente'), ('canceled', 'Cancelado')], default='valid', max_length=20, verbose_name='Status')),
                ('licensed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.licensed', verbose_name='Licenciado')),
            ],
            options={
                'verbose_name': 'Pontuação do Licenciado',
                'verbose_name_plural': 'Pontuações dos Licenciados',
                'db_table': 'LicensedPoints',
                'indexes': [models.Index(fields=['licensed'], name='LicensedPoi_license_44be04_idx'), models.Index(fields=['status'], name='LicensedPoi_status_a64ac2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnilevelNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Nível na Rede')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Registro')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('downline_licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.licensed', verbose_name='Licenciado Filho')),
                ('upline_licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.licensed', verbose_name='Licenciado Pai')),
            ],
            options={
                'verbose_name': 'Rede Unilevel',
                'verbose_name_plural': 'Rede Unilevel',
                'db_table': 'UnilevelNetwork',
                'indexes': [models.Index(fields=['upline_licensed'], name='UnilevelNet_upline__52531d_idx'), models.Index(fields=['downline_licensed'], name='UnilevelNet_downlin_427e7a_idx')],
            },
        ),
    ]
