# Generated by Django 5.2.3 on 2025-08-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensedpoints',
            options={'verbose_name': 'Pontuação', 'verbose_name_plural': 'Pontuações'},
        ),
    ]
