# Generated by Django 5.2.3 on 2025-08-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_licensedpoints_options'),
        ('network', '0002_create_product'),
    ]

    operations = [
    ]
