# Generated by Django 5.2.3 on 2025-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_merge_20250814_0205'),
    ]

    operations = [
    ]
