# Generated by Django 5.2.3 on 2025-08-16 05:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_merge_20250816_0046'),
        ('network', '0004_auto_20250816_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_amount', models.PositiveIntegerField(verbose_name='Pontos')),
                ('object_id', models.BigIntegerField(verbose_name='ID do Objeto de Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'prospect'), ('model', 'proposal')), models.Q(('app_label', 'plans'), ('model', 'planadesion')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Origem')),
                ('receiver_licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_scores', to='core.licensed', verbose_name='Licenciado Recebedor')),
                ('triggering_licensed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scores', to='core.licensed', verbose_name='Licenciado Causador da Ação')),
            ],
            options={
                'verbose_name': 'Referência de Pontuação',
                'verbose_name_plural': 'Referências de Pontuação',
                'db_table': 'ScoreReference',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver_licensed'], name='ScoreRefere_receive_7e74e7_idx'), models.Index(fields=['content_type', 'object_id'], name='ScoreRefere_content_b0bcf0_idx')],
            },
        ),
    ]
