# Generated by Django 5.2.3 on 2025-08-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_licensedpoints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scorereference',
            new_name='ScoreRefere_status_a311bd_idx',
            old_name='network_sc_status_idx',
        ),
    ]
