# Generated by Django 5.2.3 on 2025-09-01 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_licenseddocument_file'),
        ('network', '0008_rename_network_sc_status_idx_scorerefere_status_a311bd_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Bônus')),
                ('status', models.CharField(choices=[('blocked', 'Bloqueado'), ('released', 'Liberado'), ('canceled', 'Cancelado')], default='blocked', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_references', to='network.product', verbose_name='Produto Origem')),
                ('receiver_licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bonus', to='core.licensed', verbose_name='Licenciado Recebedor')),
            ],
            options={
                'verbose_name': 'Referência de Bônus',
                'verbose_name_plural': 'Referências de Bônus',
                'db_table': 'BonusReference',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver_licensed'], name='BonusRefere_receive_1fb810_idx'), models.Index(fields=['product'], name='BonusRefere_product_c4279f_idx'), models.Index(fields=['status'], name='BonusRefere_status_341f66_idx')],
            },
        ),
    ]
