# Generated by Django 5.2.3 on 2025-09-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('network', '0009_update_scoreref_contenttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorereference',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'contractor'), ('model', 'proposal')), models.Q(('app_label', 'plans'), ('model', 'planadesion')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Origem'),
        ),
    ]
