# Generated by Django 5.2.3 on 2025-09-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_bonusreference'),
        ('network', '0010_alter_scorereference_content_type'),
    ]

    operations = [
    ]
