# Generated by Django 5.2.3 on 2025-09-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_merge_20250907_0353'),
        ('network', '0011_merge_20250907_1121'),
    ]

    operations = [
    ]
