# Generated by Django 5.2.3 on 2025-07-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_affiliate', models.CharField(max_length=150, verbose_name='Nome do Afiliado')),
                ('balance_available', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Disponível')),
                ('balance_blocked', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Bloqueado')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('affiliate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to='core.affiliate', verbose_name='Afiliado')),
            ],
            options={
                'verbose_name': 'Conta Virtual',
                'verbose_name_plural': 'Contas Virtuais',
                'db_table': 'tb_VirtualAccount',
            },
        ),
    ]
