# Generated by Django 5.2.3 on 2025-08-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatewayconfig',
            options={'verbose_name': 'Gateway Config', 'verbose_name_plural': 'Gateways Configs'},
        ),
    ]
