# Generated by Django 5.2.3 on 2025-07-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('blocked', 'Bloqueado'), ('released', 'Liberado'), ('canceled', 'Cancelado')], default='blocked', max_length=20, verbose_name='Status')),
                ('operation', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], max_length=10, verbose_name='Operação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processado?')),
                ('reference_date', models.DateField(verbose_name='Data de Referência')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('virtual_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.virtualaccount', verbose_name='Conta Virtual')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'db_table': 'tb_Transaction',
            },
        ),
    ]
