# Generated by Django 5.2.3 on 2025-08-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_gatewayconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
