# Generated by Django 5.2.3 on 2025-09-24 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_licensedcompany_and_more'),
        ('finance', '0003_paymentlink_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2)),
                ('bank_code', models.CharField(max_length=10, verbose_name='Código do Banco')),
                ('bank_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome do Banco')),
                ('account_type', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('pagamento', 'Conta de Pagamento')], default='corrente', max_length=12)),
                ('agency_number', models.CharField(max_length=10)),
                ('agency_digit', models.CharField(blank=True, max_length=5, null=True)),
                ('account_number', models.CharField(max_length=20)),
                ('account_digit', models.CharField(blank=True, max_length=5, null=True)),
                ('account_holder_name', models.CharField(max_length=120)),
                ('account_holder_cpf_cnpj', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('dtt_record', models.DateTimeField(auto_now_add=True)),
                ('dtt_update', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.licensedcompany')),
                ('licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.licensed', verbose_name='Licenciado')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'BankAccount',
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('paid', 'Pago'), ('canceled', 'Cancelado'), ('rejected', 'Rejeitado')], default='pending', max_length=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraw_requests', to='finance.bankaccount')),
                ('licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='core.licensed')),
            ],
            options={
                'verbose_name': 'Solicitação de Saque',
                'verbose_name_plural': 'Solicitações de Saque',
                'db_table': 'WithdrawRequest',
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['licensed'], name='BankAccount_license_a48f95_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['owner_type'], name='BankAccount_owner_t_dcf8da_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['bank_code'], name='BankAccount_bank_co_16e829_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['licensed'], name='WithdrawReq_license_969001_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['status'], name='WithdrawReq_status_29f56c_idx'),
        ),
    ]
