# Generated by Django 5.2.3 on 2025-07-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('finance', '0003_alter_virtualaccount_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Adesão Anual', 'Plano de Adesão Anual'), ('Usina Fotovoltaica', 'Usina Fotovoltaica')], default='Adesão Anual', max_length=50, verbose_name='Product')),
                ('order_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Order ID')),
                ('charge_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Charge ID')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Paid Amount')),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Installments')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('authorized', 'Authorized'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50, verbose_name='Status')),
                ('url', models.URLField(blank=True, max_length=512, null=True, verbose_name='Payment Link URL')),
                ('barcode', models.CharField(blank=True, max_length=256, null=True, verbose_name='Barcode')),
                ('qrcode', models.CharField(blank=True, max_length=512, null=True, verbose_name='QR Code')),
                ('request_payload', models.TextField(blank=True, null=True, verbose_name='Request Payload')),
                ('response_payload', models.TextField(blank=True, null=True, verbose_name='Response Payload')),
                ('is_captured', models.BooleanField(default=False, verbose_name='Captured?')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='Canceled?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled At')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='core.affiliate')),
            ],
            options={
                'verbose_name': 'Payment Link',
                'verbose_name_plural': 'Payment Links',
            },
        ),
    ]
