# Generated by Django 5.2.3 on 2025-07-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymentlink'),
        ('plans', '0007_plan_contract_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pagarme', max_length=50)),
                ('api_token', models.CharField(max_length=255)),
                ('api_url', models.URLField(help_text='URL da API Pagarme produção. Ex.: https://api.pagar.me/core/v5/paymentlinks')),
                ('dev_url_hint', models.URLField(blank=True, help_text='URL sandbox Pagarme (só informativo). Ex.: https://sdx-api.pagar.me/core/v5/paymentlinks', null=True)),
                ('postback_url', models.URLField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paymentlink',
            options={'verbose_name': 'Link de Cobrança', 'verbose_name_plural': 'Links de Cobranças'},
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='adesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='plans.planadesion'),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='gateway',
            field=models.CharField(choices=[('pagarme', 'Pagarme'), ('pagseguro', 'PagSeguro')], default='pagarme', max_length=50, verbose_name='Gateway'),
        ),
    ]
