# Generated by Django 5.2.3 on 2025-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bankaccount_withdrawrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(default='Sicoob', max_length=50)),
                ('api_base_url', models.URLField(blank=True, null=True)),
                ('oauth_url', models.URLField(blank=True, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, help_text='Opcional (dev)', max_length=1024, null=True)),
                ('cert_path', models.CharField(blank=True, max_length=512, null=True)),
                ('key_path', models.CharField(blank=True, max_length=512, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('webhook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_user', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_password', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração PIX',
                'verbose_name_plural': 'Configurações PIX',
                'db_table': 'PixConfig',
            },
        ),
    ]
