# Generated by Django 5.2.3 on 2025-07-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_paymentconfig_alter_paymentlink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='api_url',
            field=models.URLField(help_text='URL da API Pagarme dev. Ex.: https://sdx-api.pagar.me/core/v5/paymentlinks'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='postback_url',
            field=models.URLField(blank=True, help_text='URL que será chamada como webhook.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL para redirecionar o cliente após o pagamento.', null=True),
        ),
    ]
