# Generated by Django 5.2.3 on 2025-10-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_licensedcompany_and_more'),
        ('finance', '0005_pixconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('requested', 'Solicitado'), ('approved', 'Aprovado'), ('scheduled', 'Agendado'), ('emergency_released', 'Liberação Emergencial'), ('canceled', 'Cancelado'), ('processed_paid', 'Pago'), ('processed_rejected', 'Rejeitado')], max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Saque',
                'verbose_name_plural': 'Históricos de Saque',
                'db_table': 'WithdrawRequestLog',
            },
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdraw_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_withdraw_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='emergency_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='expected_payout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_withdraw_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('scheduled', 'Agendado'), ('processing', 'Processando'), ('paid', 'Pago'), ('canceled', 'Cancelado'), ('rejected', 'Rejeitado')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['scheduled_for'], name='WithdrawReq_schedul_77fbaa_idx'),
        ),
        migrations.AddField(
            model_name='withdrawrequestlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraw_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawrequestlog',
            name='withdraw_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.withdrawrequest'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequestlog',
            index=models.Index(fields=['withdraw_request'], name='WithdrawReq_withdra_8d2b79_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequestlog',
            index=models.Index(fields=['action'], name='WithdrawReq_action_987771_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequestlog',
            index=models.Index(fields=['created_at'], name='WithdrawReq_created_dc6a79_idx'),
        ),
    ]
