# Generated by Django 5.2.3 on 2025-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_paymentconfig_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='webhook_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='webhook_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
