# Generated by Django 5.2.3 on 2025-07-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentconfig_webhook_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='webhook_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
