# Generated by Django 5.2.3 on 2025-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_paymentconfig_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Code'),
        ),
    ]
