# Generated by Django 5.2.3 on 2025-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
