# Generated by Django 5.2.3 on 2025-07-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_city_is_capital_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
