# Generated by Django 5.2.3 on 2025-08-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_remove_proposalresult_prospect_result_proposal_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='product',
        ),
    ]
