# Generated by Django 5.2.3 on 2025-08-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_remove_prospect_product'),
    ]

    operations = [
    ]
