# Generated by Django 5.2.3 on 2025-08-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_proposal_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_owner_self',
            field=models.BooleanField(default=True, verbose_name='Imóvel Próprio?'),
        ),
        migrations.CreateModel(
            name='ProposalLeadActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('contractor', 'Contratante'), ('owner', 'Proprietário'), ('legal_responsible', 'Responsável Legal')], max_length=20, verbose_name='Ator')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('st', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_actors', to='prospect.proposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Ator da Proposta',
                'verbose_name_plural': 'Atores da Proposta',
                'db_table': 'ProspectProposalLeadActor',
                'indexes': [models.Index(fields=['proposal', 'actor'], name='ProspectPro_proposa_803ca0_idx')],
                'unique_together': {('proposal', 'actor')},
            },
        ),
    ]
