# Generated by Django 5.2.3 on 2025-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_proposal_is_owner_self_proposalleadactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='monthly_consumption',
            field=models.JSONField(blank=True, null=True, verbose_name='Consumo Mensal (kWh)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_complement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_neighborhood',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_st',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contractor_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP (Contratante)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_electric_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Última Conta de Luz (R$)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_energy_provider_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Última Distribuidora (ID)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_energy_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Última Distribuidora (Nome)'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='preferred_property_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Imóvel Preferido'),
        ),
    ]
