# Generated by Django 5.2.3 on 2025-08-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0007_proposal_monthly_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='electric_bill',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='energy_provider_id',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='energy_provider_name',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='property_type',
        ),
        migrations.AddField(
            model_name='proposal',
            name='energy_provider_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distribuidora (ID)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='energy_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distribuidora (Nome)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='property_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Imóvel'),
        ),
    ]
