# Generated by Django 5.2.3 on 2025-08-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0008_remove_prospect_electric_bill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Proposta (Contractor)', 'verbose_name_plural': 'Propostas (Contractor)'},
        ),
        migrations.AlterModelOptions(
            name='proposalresult',
            options={'verbose_name': 'Resultado de Proposta (Contractor)', 'verbose_name_plural': 'Resultados de Proposta (Contractor)'},
        ),
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['-dtt_record'], 'verbose_name': 'Contractor', 'verbose_name_plural': 'Contractors'},
        ),
        migrations.RenameIndex(
            model_name='proposalleadactor',
            new_name='ContractorP_proposa_71a4e8_idx',
            old_name='ProspectPro_proposa_803ca0_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='Contractor_referen_c64bee_idx',
            old_name='Prospect_referen_234848_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='Contractor_status_b94e22_idx',
            old_name='Prospect_status_c094b7_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='Contractor_person__9f7f15_idx',
            old_name='Prospect_person__1bdd76_idx',
        ),
        migrations.AlterModelTable(
            name='proposal',
            table='ContractorProposal',
        ),
        migrations.AlterModelTable(
            name='proposalleadactor',
            table='ContractorProposalLeadActor',
        ),
        migrations.AlterModelTable(
            name='proposalresult',
            table='ContractorProposalResult',
        ),
        migrations.AlterModelTable(
            name='prospect',
            table='Contractor',
        ),
    ]
