# Generated by Django 5.2.3 on 2025-07-22 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('location', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='current_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_affiliates', to='plans.plancareer', verbose_name='Carreira Atual'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='original_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.affiliate', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plano de Adesão'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='previous_career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_affiliates', to='plans.plancareer', verbose_name='Carreira Anterior'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login desse Afiliado'),
        ),
        migrations.AddField(
            model_name='operationsmanager',
            name='city_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AddField(
            model_name='operationsmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login desse Operador'),
        ),
    ]
