# Generated by Django 5.2.3 on 2025-08-12 05:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_initial'),
        ('plans', '0002_alter_plan_bonus_level_1_alter_plan_bonus_level_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo de Usuários',
                'verbose_name_plural': 'Grupos de Usuários',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_licensed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
        migrations.AlterField(
            model_name='licensed',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.plan', verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id_document_issuer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id_document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Login Operador'),
        ),
    ]
