# Generated by Django 5.2.3 on 2025-08-14 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coregroup_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensed',
            name='original_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.licensed', verbose_name='Indicado por'),
        ),
    ]
