# Generated by Django 5.2.3 on 2025-08-14 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coregroup_alter_operator_options_and_more'),
        ('core', '0004_remove_operator_city_fields'),
    ]

    operations = [
    ]
