# Generated by Django 5.2.3 on 2025-08-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_licensed_original_indicator'),
        ('core', '0005_merge_20250813_2300'),
    ]

    operations = [
    ]
