# Generated by Django 5.2.3 on 2025-08-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250819_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('comprovante_endereco', 'Comprovante de Endereço'), ('pis', 'PIS')], max_length=30, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='licensed_documents/', verbose_name='Arquivo do Documento')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('stt_validate', models.CharField(choices=[('pending', 'Pendente'), ('rejected', 'Reprovado'), ('approved', 'Aprovado')], default='pending', max_length=10, verbose_name='Status de Validação')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Reprovação')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('licensed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.licensed', verbose_name='Licenciado')),
            ],
            options={
                'verbose_name': 'Documento do Licenciado',
                'verbose_name_plural': 'Documentos dos Licenciados',
                'db_table': 'LicensedDocument',
                'constraints': [models.UniqueConstraint(fields=('licensed', 'document_type'), name='uq_licensed_document_unique_type_per_licensed')],
            },
        ),
    ]
