# Generated by Django 5.2.3 on 2025-08-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_licenseddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensed',
            name='stt_document',
            field=models.CharField(choices=[('pending', 'Pendente'), ('rejected', 'Reprovado'), ('approved', 'Aprovado')], default='pending', max_length=10, verbose_name='Status Documentação'),
        ),
    ]
