# Generated by Django 5.2.3 on 2025-09-01 09:08

from core.models.LicensedDocument import licensed_document_upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_licensed_stt_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseddocument',
            name='file',
            field=models.FileField(upload_to=licensed_document_upload_to, verbose_name='Arquivo do Documento'),
        ),
    ]
