# Generated by Django 5.2.3 on 2025-09-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_2fa_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twofa_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twofa_secret',
        ),
    ]
