# Generated by Django 5.2.3 on 2025-09-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_twofa_enabled_remove_user_twofa_secret'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('insc_estadual', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual')),
                ('insc_municipal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('stt_validate', models.CharField(choices=[('pending', 'Pendente'), ('rejected', 'Reprovado'), ('approved', 'Aprovado')], default='pending', max_length=10, verbose_name='Status de Validação')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da Reprovação')),
                ('dtt_record', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('dtt_update', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
            ],
            options={
                'verbose_name': 'Empresa do Licenciado',
                'verbose_name_plural': 'Empresas dos Licenciados',
                'db_table': 'LicensedCompany',
            },
        ),
        migrations.RemoveConstraint(
            model_name='licenseddocument',
            name='uq_licensed_document_unique_type_per_licensed',
        ),
        migrations.AddField(
            model_name='licenseddocument',
            name='owner_type',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo do Dono do Documento (PF/PJ)'),
        ),
        migrations.AlterField(
            model_name='licenseddocument',
            name='document_type',
            field=models.CharField(choices=[('cpf', 'CPF'), ('rg', 'RG'), ('comprovante_endereco', 'Comprovante de Endereço'), ('pis', 'PIS'), ('cnpj_card', 'Cartão CNPJ'), ('social_contract', 'Contrato Social')], max_length=30, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='licensedcompany',
            name='city_lookup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.city'),
        ),
        migrations.AddField(
            model_name='licensedcompany',
            name='licensed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.licensed', verbose_name='Licenciado'),
        ),
        migrations.AddField(
            model_name='licenseddocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.licensedcompany', verbose_name='Empresa (quando PJ)'),
        ),
        migrations.AddConstraint(
            model_name='licenseddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'pf')), fields=('licensed', 'owner_type', 'document_type'), name='uq_doc_unique_type_per_licensed_pf'),
        ),
        migrations.AddConstraint(
            model_name='licenseddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('owner_type', 'pj')), fields=('company', 'document_type'), name='uq_doc_unique_type_per_company_pj'),
        ),
        migrations.AddIndex(
            model_name='licensedcompany',
            index=models.Index(fields=['licensed'], name='LicensedCom_license_bc5696_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedcompany',
            index=models.Index(fields=['cnpj'], name='LicensedCom_cnpj_e11afb_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedcompany',
            index=models.Index(fields=['stt_validate'], name='LicensedCom_stt_val_aac442_idx'),
        ),
    ]
