# Generated by Django 5.2.3 on 2025-10-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_licensedcompany_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('disabled_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rotina Agendada (Config)',
                'verbose_name_plural': 'Rotinas Agendadas (Config)',
                'db_table': 'ScheduledTaskConfig',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enable', 'Ativar'), ('disable', 'Desativar'), ('run_now', 'Executar Agora')], max_length=20)),
                ('actor_username', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.scheduledtaskconfig')),
            ],
            options={
                'verbose_name': 'Rotina Agendada (Log)',
                'verbose_name_plural': 'Rotinas Agendadas (Logs)',
                'db_table': 'ScheduledTaskLog',
                'indexes': [models.Index(fields=['config'], name='ScheduledTa_config__53b31d_idx'), models.Index(fields=['action'], name='ScheduledTa_action_43ed2d_idx'), models.Index(fields=['created_at'], name='ScheduledTa_created_067039_idx')],
            },
        ),
    ]
